{% set name = "napari-amdtrk" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-amdtrk-{{ version }}.tar.gz
  sha256: 678f7b17d103c4d3a7a862301b581b3b1c760da33ad73a2ed7c75ee5191cde07

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - magicgui
    - numpy <1.24
    - pandas
    - python >={{ python_min }}
    - pyyaml
    - qtpy
    - trackpy
    - scikit-image

test:
  imports:
    - napari_amdtrk
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://github.com/Jeff-Gui/napari-amdtrk-plugin
  summary: Manually amend segmentation and track within napari
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
